// <auto-generated />
using Explore.AdminIdentityService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Explore.AdminIdentityService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdminIdentityDbContext))]
    [Migration("20260429090000_RemoveLegacyCurrentAdminPermissions")]
    partial class RemoveLegacyCurrentAdminPermissions
    {
    }
}


